### create index customers
PUT http://localhost:9200/customers

### create index products
PUT http://localhost:9200/products

### create index orders
PUT http://localhost:9200/orders

### show all indices
GET http://localhost:9200/_cat/indices?v

### delete index customers
DELETE http://localhost:9200/customers

### delete index products
DELETE http://localhost:9200/products

### delete index orders
DELETE http://localhost:9200/orders

### show all indices
GET http://localhost:9200/_cat/indices?v

### get customers mapping
GET http://localhost:9200/customers/_mapping

### update customers mapping
PUT http://localhost:9200/customers/_mapping
Content-Type: application/json

{
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ]
}

### update customers mapping
PUT http://localhost:9200/customers/_mapping
Content-Type: application/json

{
  "numeric_detection": true
}

### get products mapping
GET http://localhost:9200/products/_mapping

### update products mapping
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ]
}

### update products mapping
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
  "numeric_detection" : true
}

### get orders mapping
GET http://localhost:9200/orders/_mapping

### update orders mapping
PUT http://localhost:9200/orders/_mapping
Content-Type: application/json

{
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ]
}

### update orders mapping
PUT http://localhost:9200/orders/_mapping
Content-Type: application/json

{
  "numeric_detection" : true
}


### create new customer
POST http://localhost:9200/customers/_create/khannedy
Content-Type: application/json

{
  "name" : "Eko Kurniawan Khannedy",
  "register_at" : "2023-10-10 00:00:00"
}

### get customers mapping
GET http://localhost:9200/customers/_mapping

### create product 1
POST http://localhost:9200/products/_create/1
Content-Type: application/json

{
  "name" : "Indomie Ayam Bawang",
  "price" : "2000"
}

### create product 2
POST http://localhost:9200/products/_create/2
Content-Type: application/json

{
  "name" : "Mie Sedap Soto",
  "price" : 2000
}

### get products mapping
GET http://localhost:9200/products/_mapping

### create order 1
POST http://localhost:9200/orders/_create/1
Content-Type: application/json

{
  "order_date": "2023-09-09 00:00:00",
  "customer_id": "khannedy",
  "total": "8000",
  "items": [
    {
      "product_id": "1",
      "price": "2000",
      "quantity": "2"
    },
    {
      "product_id": "2",
      "price": "2000",
      "quantity": "2"
    }
  ]
}

### get orders mapping
GET http://localhost:9200/orders/_mapping

### get customer khannedy
GET http://localhost:9200/customers/_doc/khannedy

### get customer notfound
GET http://localhost:9200/customers/_doc/salah

### get customer khannedy
GET http://localhost:9200/customers/_source/khannedy

### get customer notfound
GET http://localhost:9200/customers/_source/salah

### check customer khannedy
HEAD http://localhost:9200/customers/_doc/khannedy

### check customer notfound
HEAD http://localhost:9200/customers/_doc/salah

### get products 1 and 2
GET http://localhost:9200/products/_mget
Content-Type: application/json

{
  "ids" : [
    "1", "2"
  ]
}

### get order 1 and customer khannedy
GET http://localhost:9200/_mget
Content-Type: application/json

{
  "docs": [
    {
      "_id" : "1",
      "_index": "orders"
    },
    {
      "_id" : "khannedy",
      "_index": "customers"
    },
    {
      "_id" : "3",
      "_index": "products"
    }
  ]
}

### search all products
POST http://localhost:9200/products/_search

### search all products page 1
POST http://localhost:9200/products/_search?size=1&from=0

### search all products page 2
POST http://localhost:9200/products/_search?size=1&from=1

### search all products sort by price
POST http://localhost:9200/products/_search?sort=price:asc

### search all products sort by name
POST http://localhost:9200/products/_search?sort=name:desc

### create product 3
POST http://localhost:9200/products/_doc/3
Content-Type: application/json

{
  "name" : "Pop Mie Rasa Bakso",
  "price": 2500
}

### create product 4
POST http://localhost:9200/products/_doc/4
Content-Type: application/json

{
  "name" : "Samsung Galaxy S9+",
  "price": 10000000
}

### create product 5
POST http://localhost:9200/products/_doc/5
Content-Type: application/json

{
  "name" : "Acer Predator XXI",
  "price": 25000000
}

### get product 5
GET http://localhost:9200/products/_doc/5

### search all products
POST http://localhost:9200/products/_search

### update price for product 5
POST http://localhost:9200/products/_update/5
Content-Type: application/json

{
  "doc" : {
    "price": 30000000
  }
}

### insert customer spammer
POST http://localhost:9200/customers/_create/spammer
Content-Type: application/json

{
  "name" : "spammer",
  "register_at" : "2023-10-10 00:00:00"
}

### delete customer spammer
DELETE http://localhost:9200/customers/_doc/spammer
